### ISSUE TITLE
Remove unnecessary usage of `eval`

### ISSUE THREAD

**Issue by MSE99** [ZaidMade/CatRat#1]
the `Entity` class in the object.js file uses eval twice in it's constructor.

https://github.com/ZaidMade/CatRat/blob/master/src/objects.js#L6
https://github.com/ZaidMade/CatRat/blob/master/src/objects.js#L7

This could easily be fixed by just using computed property keys instead of running JS code from strings.

```javascript
this.type = types[_type];
this.sprite = sprites[_type];
``` 

I know that this isn't a real issue, but i don't really understand why `eval` is used. 
i really like this game and would like to see it get finished.

**Comment by ZaidMade** [comment]
> I know that this isn't a real issue, but i don't really understand why `eval` is used.

I was working very quickly on this project at the time and clearly made a few simple mistakes. Now that you've pointed it out though, no clue what I was thinking. I was prioritizing just getting it to work over everything else.

I also noticed an unnecessary inline if statement right below that.
`this.bop = ((Math.random() >= 0.5) ? true : false);`

Thank you for playing around with it, giving feedback and showing interest! Makes me want to get back to working on this again!
